package sys.db.pgsql;
typedef ErrorMessageObject = {
	severity_type : SeverityType;
	code          : SQLSTATE;
	message       : String;
	?detail       : String;
	?hint         : String;
	?position     : String;
	?query        : String;
	?where        : String;
	?file         : String;
	?line         : String;
	?routine      : String;
}

@:fakeEnum
abstract SeverityType(String) from String to String{
	public static var ERROR   = "ERROR";
	public static var FATAL   = "FATAL";
	public static var PANIC   = "PANIC";
	public static var WARNING = "WARNING";
	public static var NOTICE  = "NOTICE";
	public static var DEBUG   = "DEBUG"
	public static var INFO    = "INFO";
	public static var LOG     = "LOG";
}

@:fakeEnum
abstract SQLState(String) from String to String {
	public static var successful_completion                                = "0";		// Class 00 — Successful Completion
	public static var warning                                              = "1000";	// Class 01 — Warning
	public static var dynamic_result_sets_returned                         = "0100C"; 
	public static var implicit_zero_bit_padding                            = "1008"; 
	public static var null_value_eliminated_in_set_function                = "1003"; 
	public static var privilege_not_granted                                = "1007"; 
	public static var privilege_not_revoked                                = "1006"; 
	public static var string_data_right_truncation                         = "1004"; 
	public static var deprecated_feature                                   = "01P01"; 
	public static var no_data                                              = "2000";	// Class 02 — No Data (this is also a warning class per the SQL standard)
	public static var no_additional_dynamic_result_sets_returned           = "2001"; 
	public static var sql_statement_not_yet_complete                       = "3000";	// Class 03 — SQL Statement Not Yet Complete
	public static var connection_exception                                 = "8000";	// Class 08 — Connection Exception
	public static var connection_does_not_exist                            = "8003"; 
	public static var connection_failure                                   = "8006"; 
	public static var sqlclient_unable_to_establish_sqlconnection          = "8001"; 
	public static var sqlserver_rejected_establishment_of_sqlconnection    = "8004"; 
	public static var transaction_resolution_unknown                       = "8007"; 
	public static var protocol_violation                                   = "08P01"; 
	public static var triggered_action_exception                           = "9000";	// Class 09 — Triggered Action Exception
	public static var feature_not_supported                                = "0A000";	// Class 0A — Feature Not Supported
	public static var invalid_transaction_initiation                       = "0B000";	// Class 0B — Invalid Transaction Initiation
	public static var locator_exception                                    = "0F000";	// Class 0F — Locator Exception
	public static var invalid_locator_specification                        = "0F001"; 
	public static var invalid_grantor                                      = "0L000";	// Class 0L — Invalid Grantor
	public static var invalid_grant_operation                              = "0LP01"; 
	public static var invalid_role_specification                           = "0P000";	// Class 0P — Invalid Role Specification
	public static var diagnostics_exception                                = "0Z000";	// Class 0Z — Diagnostics Exception
	public static var stacked_diagnostics_accessed_without_active_handler  = "0Z002"; 
	public static var case_not_found                                       = "20000";	// Class 20 — Case Not Found
	public static var cardinality_violation                                = "21000";	// Class 21 — Cardinality Violation
	public static var data_exception                                       = "22000";	// Class 22 — Data Exception
	public static var array_subscript_error                                = "2202E"; 
	public static var character_not_in_repertoire                          = "22021"; 
	public static var datetime_field_overflow                              = "22008"; 
	public static var division_by_zero                                     = "22012"; 
	public static var error_in_assignment                                  = "22005"; 
	public static var escape_character_conflict                            = "2200B"; 
	public static var indicator_overflow                                   = "22022"; 
	public static var interval_field_overflow                              = "22015"; 
	public static var invalid_argument_for_logarithm                       = "2201E"; 
	public static var invalid_argument_for_ntile_function                  = "22014"; 
	public static var invalid_argument_for_nth_value_function              = "22016"; 
	public static var invalid_argument_for_power_function                  = "2201F"; 
	public static var invalid_argument_for_width_bucket_function           = "2201G"; 
	public static var invalid_character_value_for_cast                     = "22018"; 
	public static var invalid_datetime_format                              = "22007"; 
	public static var invalid_escape_character                             = "22019"; 
	public static var invalid_escape_octet                                 = "2200D"; 
	public static var invalid_escape_sequence                              = "22025"; 
	public static var nonstandard_use_of_escape_character                  = "22P06"; 
	public static var invalid_indicator_parameter_value                    = "22010"; 
	public static var invalid_parameter_value                              = "22023"; 
	public static var invalid_regular_expression                           = "2201B"; 
	public static var invalid_row_count_in_limit_clause                    = "2201W"; 
	public static var invalid_row_count_in_result_offset_clause            = "2201X"; 
	public static var invalid_time_zone_displacement_value                 = "22009"; 
	public static var invalid_use_of_escape_character                      = "2200C"; 
	public static var most_specific_type_mismatch                          = "2200G"; 
	public static var null_value_not_allowed                               = "22004"; 
	public static var null_value_no_indicator_parameter                    = "22002"; 
	public static var numeric_value_out_of_range                           = "22003"; 
	public static var string_data_length_mismatch                          = "22026"; 
	public static var string_data_right_truncation                         = "22001"; 
	public static var substring_error                                      = "22011"; 
	public static var trim_error                                           = "22027"; 
	public static var unterminated_c_string                                = "22024"; 
	public static var zero_length_character_string                         = "2200F"; 
	public static var floating_point_exception                             = "22P01"; 
	public static var invalid_text_representation                          = "22P02"; 
	public static var invalid_binary_representation                        = "22P03"; 
	public static var bad_copy_file_format                                 = "22P04"; 
	public static var untranslatable_character                             = "22P05"; 
	public static var not_an_xml_document                                  = "2200L"; 
	public static var invalid_xml_document                                 = "2200M"; 
	public static var invalid_xml_content                                  = "2200N"; 
	public static var invalid_xml_comment                                  = "2200S"; 
	public static var invalid_xml_processing_instruction                   = "2200T"; 
	public static var integrity_constraint_violation                       = "23000";	// Class 23 — Integrity Constraint Violation
	public static var restrict_violation                                   = "23001"; 
	public static var not_null_violation                                   = "23502"; 
	public static var foreign_key_violation                                = "23503"; 
	public static var unique_violation                                     = "23505"; 
	public static var check_violation                                      = "23514"; 
	public static var exclusion_violation                                  = "23P01"; 
	public static var invalid_cursor_state                                 = "24000";	// Class 24 — Invalid Cursor State
	public static var invalid_transaction_state                            = "25000";	// Class 25 — Invalid Transaction State
	public static var active_sql_transaction                               = "25001"; 
	public static var branch_transaction_already_active                    = "25002"; 
	public static var held_cursor_requires_same_isolation_level            = "25008"; 
	public static var inappropriate_access_mode_for_branch_transaction     = "25003"; 
	public static var inappropriate_isolation_level_for_branch_transaction = "25004"; 
	public static var no_active_sql_transaction_for_branch_transaction     = "25005"; 
	public static var read_only_sql_transaction                            = "25006"; 
	public static var schema_and_data_statement_mixing_not_supported       = "25007"; 
	public static var no_active_sql_transaction                            = "25P01"; 
	public static var in_failed_sql_transaction                            = "25P02"; 
	public static var invalid_sql_statement_name                           = "26000";	// Class 26 — Invalid SQL Statement Name
	public static var triggered_data_change_violation                      = "27000";	// Class 27 — Triggered Data Change Violation
	public static var invalid_authorization_specification                  = "28000";	// Class 28 — Invalid Authorization Specification
	public static var invalid_password                                     = "28P01"; 
	public static var dependent_privilege_descriptors_still_exist          = "2B000";	// Class 2B — Dependent Privilege Descriptors Still Exist
	public static var dependent_objects_still_exist                        = "2BP01"; 
	public static var invalid_transaction_termination                      = "2D000";	// Class 2D — Invalid Transaction Termination
	public static var sql_routine_exception                                = "2F000";	// Class 2F — SQL Routine Exception
	public static var function_executed_no_return_statement                = "2F005"; 
	public static var modifying_sql_data_not_permitted                     = "2F002"; 
	public static var prohibited_sql_statement_attempted                   = "2F003"; 
	public static var reading_sql_data_not_permitted                       = "2F004"; 
	public static var invalid_cursor_name                                  = "34000";	// Class 34 — Invalid Cursor Name
	public static var external_routine_exception                           = "38000";	// Class 38 — External Routine Exception
	public static var containing_sql_not_permitted                         = "38001"; 
	public static var modifying_sql_data_not_permitted                     = "38002"; 
	public static var prohibited_sql_statement_attempted                   = "38003"; 
	public static var reading_sql_data_not_permitted                       = "38004"; 
	public static var external_routine_invocation_exception                = "39000";	// Class 39 — External Routine Invocation Exception
	public static var invalid_sqlstate_returned                            = "39001"; 
	public static var null_value_not_allowed                               = "39004"; 
	public static var trigger_protocol_violated                            = "39P01"; 
	public static var srf_protocol_violated                                = "39P02"; 
	public static var savepoint_exception                                  = "3B000";	// Class 3B — Savepoint Exception
	public static var invalid_savepoint_specification                      = "3B001"; 
	public static var invalid_catalog_name                                 = "3D000";	// Class 3D — Invalid Catalog Name
	public static var invalid_schema_name                                  = "3F000";	// Class 3F — Invalid Schema Name
	public static var transaction_rollback                                 = "40000";	// Class 40 — Transaction Rollback
	public static var transaction_integrity_constraint_violation           = "40002"; 
	public static var serialization_failure                                = "40001"; 
	public static var statement_completion_unknown                         = "40003"; 
	public static var deadlock_detected                                    = "40P01"; 
	public static var syntax_error_or_access_rule_violation                = "42000";	// Class 42 — Syntax Error or Access Rule Violation
	public static var syntax_error                                         = "42601"; 
	public static var insufficient_privilege                               = "42501"; 
	public static var cannot_coerce                                        = "42846"; 
	public static var grouping_error                                       = "42803"; 
	public static var windowing_error                                      = "42P20"; 
	public static var invalid_recursion                                    = "42P19"; 
	public static var invalid_foreign_key                                  = "42830"; 
	public static var invalid_name                                         = "42602"; 
	public static var name_too_long                                        = "42622"; 
	public static var reserved_name                                        = "42939"; 
	public static var datatype_mismatch                                    = "42804"; 
	public static var indeterminate_datatype                               = "42P18"; 
	public static var collation_mismatch                                   = "42P21"; 
	public static var indeterminate_collation                              = "42P22"; 
	public static var wrong_object_type                                    = "42809"; 
	public static var undefined_column                                     = "42703"; 
	public static var undefined_function                                   = "42883"; 
	public static var undefined_table                                      = "42P01"; 
	public static var undefined_parameter                                  = "42P02"; 
	public static var undefined_object                                     = "42704"; 
	public static var duplicate_column                                     = "42701"; 
	public static var duplicate_cursor                                     = "42P03"; 
	public static var duplicate_database                                   = "42P04"; 
	public static var duplicate_function                                   = "42723"; 
	public static var duplicate_prepared_statement                         = "42P05"; 
	public static var duplicate_schema                                     = "42P06"; 
	public static var duplicate_table                                      = "42P07"; 
	public static var duplicate_alias                                      = "42712"; 
	public static var duplicate_object                                     = "42710"; 
	public static var ambiguous_column                                     = "42702"; 
	public static var ambiguous_function                                   = "42725"; 
	public static var ambiguous_parameter                                  = "42P08"; 
	public static var ambiguous_alias                                      = "42P09"; 
	public static var invalid_column_reference                             = "42P10"; 
	public static var invalid_column_definition                            = "42611"; 
	public static var invalid_cursor_definition                            = "42P11"; 
	public static var invalid_database_definition                          = "42P12"; 
	public static var invalid_function_definition                          = "42P13"; 
	public static var invalid_prepared_statement_definition                = "42P14"; 
	public static var invalid_schema_definition                            = "42P15"; 
	public static var invalid_table_definition                             = "42P16"; 
	public static var invalid_object_definition                            = "42P17"; 
	public static var with_check_option_violation                          = "44000";	// Class 44 — WITH CHECK OPTION Violation
	public static var insufficient_resources                               = "53000";	// Class 53 — Insufficient Resources
	public static var disk_full                                            = "53100"; 
	public static var out_of_memory                                        = "53200"; 
	public static var too_many_connections                                 = "53300"; 
	public static var configuration_limit_exceeded                         = "53400"; 
	public static var program_limit_exceeded                               = "54000";	// Class 54 — Program Limit Exceeded
	public static var statement_too_complex                                = "54001"; 
	public static var too_many_columns                                     = "54011"; 
	public static var too_many_arguments                                   = "54023"; 
	public static var object_not_in_prerequisite_state                     = "55000";	// Class 55 — Object Not In Prerequisite State
	public static var object_in_use                                        = "55006"; 
	public static var cant_change_runtime_param                            = "55P02"; 
	public static var lock_not_available                                   = "55P03"; 
	public static var operator_intervention                                = "57000";	// Class 57 — Operator Intervention
	public static var query_canceled                                       = "57014"; 
	public static var admin_shutdown                                       = "57P01"; 
	public static var crash_shutdown                                       = "57P02"; 
	public static var cannot_connect_now                                   = "57P03"; 
	public static var database_dropped                                     = "57P04"; 
	public static var system_error                                         = "58000";	// Class 58 — System Error (errors external to PostgreSQL itself)
	public static var io_error                                             = "58030"; 
	public static var undefined_file                                       = "58P01"; 
	public static var duplicate_file                                       = "58P02"; 
	public static var config_file_error                                    = "F0000";	// Class F0 — Configuration File Error
	public static var lock_file_exists                                     = "F0001"; 
	public static var fdw_error                                            = "HV000";	// Class HV — Foreign Data Wrapper Error (SQL/MED)
	public static var fdw_column_name_not_found                            = "HV005"; 
	public static var fdw_dynamic_parameter_value_needed                   = "HV002"; 
	public static var fdw_function_sequence_error                          = "HV010"; 
	public static var fdw_inconsistent_descriptor_information              = "HV021"; 
	public static var fdw_invalid_attribute_value                          = "HV024"; 
	public static var fdw_invalid_column_name                              = "HV007"; 
	public static var fdw_invalid_column_number                            = "HV008"; 
	public static var fdw_invalid_data_type                                = "HV004"; 
	public static var fdw_invalid_data_type_descriptors                    = "HV006"; 
	public static var fdw_invalid_descriptor_field_identifier              = "HV091"; 
	public static var fdw_invalid_handle                                   = "HV00B"; 
	public static var fdw_invalid_option_index                             = "HV00C"; 
	public static var fdw_invalid_option_name                              = "HV00D"; 
	public static var fdw_invalid_string_length_or_buffer_length           = "HV090"; 
	public static var fdw_invalid_string_format                            = "HV00A"; 
	public static var fdw_invalid_use_of_null_pointer                      = "HV009"; 
	public static var fdw_too_many_handles                                 = "HV014"; 
	public static var fdw_out_of_memory                                    = "HV001"; 
	public static var fdw_no_schemas                                       = "HV00P"; 
	public static var fdw_option_name_not_found                            = "HV00J"; 
	public static var fdw_reply_handle                                     = "HV00K"; 
	public static var fdw_schema_not_found                                 = "HV00Q"; 
	public static var fdw_table_not_found                                  = "HV00R"; 
	public static var fdw_unable_to_create_execution                       = "HV00L"; 
	public static var fdw_unable_to_create_reply                           = "HV00M"; 
	public static var fdw_unable_to_establish_connection                   = "HV00N"; 
	public static var plpgsql_error                                        = "P0000";	// Class P0 — PL/pgSQL Error
	public static var raise_exception                                      = "P0001"; 
	public static var no_data_found                                        = "P0002"; 
	public static var too_many_rows                                        = "P0003"; 
	public static var internal_error                                       = "XX000";	// Class XX — Internal Error
	public static var data_corrupted                                       = "XX001"; 
	public static var index_corrupted                                      = "XX002"; 
}


